accent = "#70b0ff"
cursor = "#fab795"
foreground = "#abb2bf"
background = "#1c1e26"
selection_foreground = "#d5d8da"
selection_background = "#2f3341"

color0  = "#1c1e26"
color1  = "#e95678"
color2  = "#64d1a9"
color3  = "#ffd88c"
color4  = "#70b0ff"
color5  = "#b877db"
color6  = "#34d3fb"
color7  = "#abb2bf"
color8  = "#5c6e80"
color9  = "#ff5555"
color10 = "#a6cc70"
color11 = "#ff9668"
color12 = "#7fdaff"
color13 = "#f3c1ff"
color14 = "#7fdaff"
color15 = "#d5d8da"
